name: MobSpawnControl
main: net.yeticraft.xxtraineexx.mobspawncontrol.MobSpawnControl
version: 1.0
authors: [XxTRAINEExX]

commands:
  msc:
    description: Interact with Mob Spawn Control
    usage: /<command>
  mobspawncontrol:
    description: Interact with Mob Spawn Control
    usage: /<command>
permissions:
    msc.*:
        description: Gives access to all MobSpawnControl features
        children:
            ff.command: true
            ff.stats: true
            ff.tp: true
    msc.command:
        description: Allows player access to MSC commands
        default: op
    msc.stats:
        description: Allows players access to STATS command
        default: op
    msc.tp:
        description: Allows players access to TP command
        default: op